name: Sync Attendance Reports

on:
  schedule:
    # Runs every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  sync-directory:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes
    
    steps:
    - name: Checkout source repo (public)
      uses: actions/checkout@v4
      with:
        repository: MohammadHamdi11/RN-E-attendancerecorderapp
        path: source-repo
    
    - name: Checkout destination repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: dest-repo
    
    - name: Copy directories
      run: |
        # Remove old directories if they exist
        rm -rf dest-repo/attendance_reports
        rm -rf dest-repo/modules_schedules
        rm -rf dest-repo/assets
        
        # Copy the directories from source to destination
        cp -r source-repo/attendance_reports dest-repo/attendance_reports
        cp -r source-repo/modules_schedules dest-repo/modules_schedules
        cp -r source-repo/assets dest-repo/assets
    
    - name: Commit and push changes
      run: |
        cd dest-repo
        git config --local user.email "action@github.com"
        git config --local user.name "Attendance Bot"
        git add attendance_reports modules_schedules assets
        
        # Only commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        git commit -m "Sync attendance_reports, modules_schedules, and assets from main repo - $(date '+%Y-%m-%d %H:%M:%S')"
        
        # Retry logic with exponential backoff
        max_attempts=5
        attempt=1
        while [ $attempt -le $max_attempts ]; do
          echo "Push attempt $attempt of $max_attempts"
          
          if git push; then
            echo "Push successful"
            exit 0
          fi
          
          echo "Push failed, pulling and retrying..."
          git pull --rebase origin main
          
          if [ $attempt -eq $max_attempts ]; then
            echo "Max attempts reached, failing"
            exit 1
          fi
          
          sleep $((2 ** attempt))  # Exponential backoff: 2s, 4s, 8s, 16s
          attempt=$((attempt + 1))
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
